version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: survey_monitor_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: survey_monitor
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - survey_monitor_network
    command: --default-authentication-plugin=mysql_native_password

  # PHP-FPM for Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: survey_monitor_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - survey_monitor_network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=survey_monitor
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: survey_monitor_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - survey_monitor_network
    depends_on:
      - app

  # Redis for Caching and Sessions
  redis:
    image: redis:alpine
    container_name: survey_monitor_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    networks:
      - survey_monitor_network

  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: survey_monitor_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    networks:
      - survey_monitor_network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  survey_monitor_network:
    driver: bridge

