version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: survey_monitor_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: survey_monitor
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: survey_user
      MYSQL_PASSWORD: survey_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - survey_monitor_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: survey_monitor_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      - redis
    networks:
      - survey_monitor_network

  nginx:
    image: nginx:alpine
    container_name: survey_monitor_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - survey_monitor_network

  redis:
    image: redis:alpine
    container_name: survey_monitor_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - survey_monitor_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: survey_monitor_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - survey_monitor_network

volumes:
  mysql_data:
  redis_data:

networks:
  survey_monitor_network:
    driver: bridge
